version: "3"

services:
  app:
    container_name: frontend
    build:
      args:
        - VITE_GATEWAY_URL=${VITE_GATEWAY_URL}
        - VITE_DOMAIN=${VITE_DOMAIN}
      context: .
    ports:
      - "80:8080"
