import { Subject } from "./types";

export const subjects: Subject[] = [
  {
    id: 1,
    name: "Software Engineerssssssssssssssssssssssssssssssssssssssssssssssssssssssqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqs",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [
      {
        id: 1,
        subjectId: 1,
        comments: [
          {
            id: 1,
            subjectId: 1,
            description:
              "This is comment1 from topic about carqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
          {
            id: 1,
            subjectId: 1,
            description: "This is comment1 from topic about car",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
          {
            id: 1,
            subjectId: 1,
            description: "This is comment1 from topic about car",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
          {
            id: 1,
            subjectId: 1,
            description: "This is comment1 from topic about car",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
          {
            id: 1,
            subjectId: 1,
            description: "This is comment1 from topic about car",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
          {
            id: 1,
            subjectId: 1,
            description: "This is comment1 from topic about car",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
          {
            id: 1,
            subjectId: 1,
            description: "This is comment1 from topic about car",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
        ],
        TopicCreatorId: 1,
        description:
          "Topic about carssssssssssssssssssssssssssssssssssssssssssssssssssssssqqqqqqqqqqqqqqqqqqqqqwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwss",
        createAt: new Date(),
      },
      {
        id: 2,
        subjectId: 1,
        comments: [
          {
            id: 1,
            subjectId: 1,
            description: "This is comment1 from topic about car2",
            CommenterId: 1,
            createAt: new Date(),
            topicId: 1,
          },
        ],
        TopicCreatorId: 1,
        description: "Last Book in this subject ?",
        createAt: new Date(),
      },
    ],
    files: [
      {
        name: "File1sssssssssssssssssssssssssssssssssssssssssssssssssssssssssxxzxzxsdasd",
        createAt: new Date(),
      },
      { name: "File2", createAt: new Date() },
    ],
    star: true,
  },
  {
    id: 2,
    name: "Data Science",
    year: 3,
    semester: 1,
    section: 3,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [
      {
        id: 2,
        subjectId: 1,
        comments: [],
        TopicCreatorId: 1,
        description: "Last Book in this subject ?",
        createAt: new Date(),
      },
    ],
    files: [],
    star: true,
  },
  {
    id: 3,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 4,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 5,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 6,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 7,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 8,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 9,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 10,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 11,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
  {
    id: 12,
    name: "Software Engineer",
    year: 1,
    semester: 2,
    section: 21,
    instructors: [],
    description: "string",
    prerequisites: [],
    topics: [],
    files: [],
  },
];
